FROM harbor-registry.atlantishq.de/atlantishq/neroxis-mapgen

RUN apt update
RUN apt install -y python3 python3-pip --no-install-recommends
RUN rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY ./worker/worker.py .

COPY requirements-mapgen-worker.txt .
RUN python3 -m pip install --no-cache-dir --break-system-packages -r requirements-mapgen-worker.txt

ENTRYPOINT ["python3"] 
CMD ["/app/worker.py"]
