# ---- Build stage ----
FROM eclipse-temurin:25-jdk AS build

WORKDIR /build

# Copy repository
COPY NeroxisMapGenerator/ .

# Build jar
RUN chmod +x gradlew 

RUN ./gradlew assemble

# ---- Runtime stage ----
FROM eclipse-temurin:25-jre

WORKDIR /

# Copy generated jar to /
COPY --from=build /build/generator/build/libs/NeroxisGen_snapshot.jar /NeroxisMapGenerator.jar

# Default command
ENTRYPOINT ["java", "-jar", "/NeroxisMapGenerator.jar"]
