FROM alpine

RUN apk add --no-cache py3-pip

WORKDIR /app

COPY ./*.py .
COPY ./utils utils
COPY ./routes routes
COPY ./database database

RUN mkdir /app/output

RUN python3 -m pip install --no-cache-dir --break-system-packages waitress

COPY ./requirements-server.txt .
RUN python3 -m pip install --no-cache-dir --break-system-packages -r requirements-server.txt

EXPOSE 5000/tcp

ENTRYPOINT ["waitress-serve"] 
CMD ["--host", "0.0.0.0", "--port", "5000",  "--threads=16", "--call", "app:createApp"]
