export const FILTERS = [
    {
        key: "map_size",
        label: "Map Size",
        type: "slider",
        min: 256,
        max: 2048,
        step: 64,
        defaultValue: 1024,
    },
    {
        key: "spawn_count",
        label: "Spawn Count",
        type: "slider",
        min: 2,
        max: 16,
        step: 1,
        defaultValue: 12,
    },
    {
        key: "num_teams",
        label: "Teams",
        type: "slider",
        min: 0,
        max: 8,
        step: 1,
        defaultValue: 2,
    },
    {
        key: "style",
        label: "Style",
        type: "select",
        options: [
            "BASIC",
            "BIG_ISLANDS",
            "CENTER_LAKE",
            "DROP_PLATEAU",
            "FLOODED",
            "HIGH_RECLAIM",
            "LAND_BRIDGE",
            "LITTLE_MOUNTAIN",
            "LOW_MEX",
            "MOUNTAIN_RANGE",
            "MULTILEVEL",
            "ONE_ISLAND",
            "SMALL_ISLANDS",
            "VALLEY",
            "RIVERS",
            "RIVERS_AND_OCEANS",
            "FRACTAL_LAND",
            "FRACTAL_PLATEAU",
            "FRACTAL_NAVY",
            "SETONISH",
            "FORREST_SOMETHING",
        ],
    },
    /*
    {
        key: "visibility",
        label: "Visibility",
        type: "select",
        options: ["TOURNAMENT", "BLIND", "UNEXPLORED"],
    },
    */
    {
        key: "terrain_symmetry",
        label: "Terrain Symmetry",
        type: "select",
        options: [
            "POINT2",
            //"POINT3",
            "POINT4",
            //"POINT5",
            "POINT6",
            //"POINT7",
            "POINT8",
            //"POINT9",
            "POINT10",
            //"POINT11",
            "POINT12",
            //"POINT13",
            "POINT14",
            //"POINT15",
            "POINT16",
            "XZ",
            "ZX",
            "X",
            "Z",
            "QUAD",
            "DIAG",
            "NONE",
        ],
    },
    {
        key: "texture_style",
        label: "Texture Style",
        type: "select",
        options: [
            "BRIMSTONE",
            "DESERT",
            "EARLYAUTUMN",
            "FRITHEN",
            "MARS",
            "MOONLIGHT",
            "PRAYER",
            "STONES",
            "SUNSET",
            "SYRTIS",
            "WINDINGRIVER",
            "WONDER",
            "CRYSTALLINE",
        ],
    },
    {
        key: "terrain_style",
        label: "Terrain Style",
        type: "select",
        options: [
            "BASIC",
            "BIG_ISLANDS",
            "CENTER_LAKE",
            "DROP_PLATEAU",
            "FLOODED",
            "LAND_BRIDGE",
            "LITTLE_MOUNTAIN",
            "MOUNTAIN_RANGE",
            "ONE_ISLAND",
            "SMALL_ISLANDS",
            "VALLEY",
            "RIVERS",
            "RIVERS_AND_OCEANS",
            "FRACTAL_LAND",
            "FRACTAL_PLATEAU",
            "FRACTAL_NAVY",
            "SETONS",
        ],
    },
    {
        key: "resource_style",
        label: "Resource Style",
        type: "select",
        options: [
            "BASIC",
            "LOW_MEX",
            "WATER_MEX",
            "HI_MEX_LAND_LOW_MEX_WATER",
            "ONE_HYDRO_NO_MEX",
        ],
    },
    {
        key: "prop_style",
        label: "Prop Style",
        type: "select",
        options: [
            "BASIC",
            "BOULDER_FIELD",
            "ENEMY_CIV",
            "HIGH_RECLAIM",
            "LARGE_BATTLE",
            "NAVY_WRECKS",
            "NEUTRAL_CIV",
            "ROCK_FIELD",
            "SMALL_BATTLE",
            "FORREST_SOMETHING",
        ],
    },
    {
        key: "reclaim_density",
        label: "Reclaim Density",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.01,
    },
    {
        key: "resource_density",
        label: "Resource Density",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.01,
    },
];
